project_identifier: shoppingfeed-webapp
api_key: dc0f39e6f60a18004cfd44c27c97f9f3
base_path: .

files:
  -
    source: '/src/**/*.html'
    translation: '/locale/%two_letters_code%/LC_MESSAGES/%original_file_name%'
