version: "3"
services:
  webapp:
    image: 813931216550.dkr.ecr.eu-west-1.amazonaws.com/webapp:dev
    networks:
    - sf_network
    volumes:
    - "$PWD:/var/www"
    environment:
      ENV: dev
      HOST: app.shopping-feed.lan
      PORT: 80
    labels:
      traefik.frontend.rule: "Host:app.shopping-feed.lan;PathPrefix:/v3"
      traefik.frontend.entryPoints: "http"
      traefik.backend: "webapp"
      traefik.protocol: "http"
      traefik.port: "80"
      traefik.docker.network: "sf_network"
networks:
  sf_network:
    external: true