version: "3"
services:
  webui:
    image: ghcr.io/shoppingflux/webui-dev:latest
    networks:
    - sf_network
    volumes:
    - "$PWD:/var/www"
    environment:
      ENV: dev
      HOST: app.shopping-feed.lan
      PORT: 80
    labels:
      traefik.webapp.frontend.rule: "Host:app.shopping-feed.lan;PathPrefix:/v3"
      traefik.docker.network: "sf_network"
      traefik.enable: "true"

  weboperator:
    image: ghcr.io/shoppingflux/operator-dev:latest
    networks:
    - sf_network
    volumes:
    - "$PWD:/var/www"
    environment:
      ENV: dev
      HOST: operator.shopping-feed.lan
      PORT: 80
    labels:
      traefik.weboperator.frontend.rule: "Host:operator.shopping-feed.lan"
      traefik.docker.network: "sf_network"
      traefik.enable: "true"

  webadmin:
    image: ghcr.io/shoppingflux/webadmin-dev:latest
    networks:
      - sf_network
    volumes:
      - "$PWD:/var/www"
    environment:
      ENV: dev
      HOST: admin.shopping-feed.lan
      PORT: 80
    labels:
      traefik.webadmin.frontend.rule: "Host:admin.shopping-feed.lan"
      traefik.docker.network: "sf_network"
      traefik.enable: "true"
networks:
  sf_network:
    external: true
