// dev environment
// please, update a docker file ARG variables if you update this file
export const environment = {
    production: 'false',
    DEFAULT_LANGUAGE: 'fr',
    APP_URL: '//app.shopping-feed.lan',
    APP_AUTHORIZATION: 'Bearer 33bb2cc5944579049fcdcaddb3144886726cfb9b',
    API_URL_WITHOUT_VERSION: '//api.shopping-feed.lan',
    API_URL: '//api.shopping-feed.lan/v1',
    API_DOCUMENTATION: 'https://developer.shopping-feed.com',
    BASE_HREF: '/v3',
    SHOPIFY_APP_URL: 'https://apps.shopify.com/shopping-feed-dev',
    SUPPORT_URL: 'https://shoppingfeed.zendesk.com/hc',
    SUPPORT_AUTHORIZATION: 'Basic ZGV2ZWxvcGVyQHNob3BwaW5nLWZlZWQuY29tOiYqRUZtMn1NK1BxeD5cUXM=',
    CONTACT_EMAIL: 'contact@shopping-feed.com',
    SUPPORT_EMAIL: 'support@shopping-feed.com',
    DEFAULT_AUTOPILOT_EMAIL: 'default@shopping-feed.com',
    DEFAULT_AUTOPILOT_STORENAME: 'default',
    RUN_AUTOPILOT: true,
    GTAG_ID: 'UA-78261662-1',
    FULLSTORY_ORG_ID: 'D6X8Q',
    ZAPIER_LINK: 'https://zapier.com/developer/invite/100387/80c3075b8660cd0602a9eb253b89ad07',
    CDISCOUNT_TRACKING_LINK: 'http://track.cdiscount-affiliation.com/servlet/effi.redir?id_compteur=22032794&url=',
    maxApiLimit: '200',
    // Zendesk widget
    zeAccountLink: 'shoppingfeed.zendesk.com',
    zeChatTitle: 'Chat Shopping Feed',
    zeConciergeName: 'Team Shopping Feed',
    zeConciergeTitle: 'I can answer all your questions!',
    zeConciergeTitleFr: 'Posez-nous toutes vos questions',
};
