export enum SftMenuTab {
    rules = 'rules',
    autoRemove = 'auto-remove',
    manage = 'manage',
    newFields = 'new-fields',
    repricing = 'repricing',
    sourceFeed = 'source-feed',
    customFeed = 'custom-feed',
    filters = 'filters',
    newProducts = 'new-products',
    settingsGeneral = 'general',
    marketplace = 'marketplace',
    shoppingEngine = 'shopping-engine',
    parameters = 'parameters',
    margin = 'margin',
    compare = 'compare',
    export = 'export',
    settingsGlobal = 'general',
    team = 'team',
    analytics = 'analytics',
    developers = 'developers',
    transformations = 'transformations',
    segmentation = 'segmentation',

    allChannels = 'all-channels',
    connectedChannels = 'connected-channels',
    customFeeds = 'custom-feeds',
}
